BookStore.WebUI/Models/BookListViewModel.cs
using BookStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookStore.WebUI.Models
{
    public class BookListViewModel
    {
        public IEnumerable<Book> Books { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentSpecilization { get; set; }
    }
}

BookStore.WebUI/Models/CartIndexViewModel.cs
using BookStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }

    }
}

BookStore.WebUI/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BookStore.WebUI.Models
{
    public class LoginViewModel
    {
        [Required]
        public string UserName { get; set; }

        [Required]
        public string Password { get; set; }



    }
}

BookStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookStore.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages
        {
            get { return Convert.ToInt32(Math.Ceiling((decimal) TotalItems / ItemPerPage)); }
        }



    }
}

BookStore.WebUI/Controllers/AccountController.cs
using BookStore.WebUI.Infrastructure.Abstract;
using BookStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    public class AccountController : Controller
    {
        private IAuthProvider authProvider;
        public AccountController(IAuthProvider auth)
        {
            authProvider = auth;
        }

        public ViewResult Login()
        {
            return View();
        }

        [HttpPost]
        // GET: Account
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (authProvider.Authenticate(model.UserName, model.Password))
                {
                    return Redirect(returnUrl ?? Url.Action("Index", "Admin"));
                }
                else
                {
                    ModelState.AddModelError("", "Incorrect UserName/Password");
                    return View();
                }
            }
            else
            {
                return View();
            }
            
        }
    }
}

BookStore.WebUI/Controllers/AdminController.cs
using BookStore.Domain.Abstract;
using BookStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    //[Authorize]
    public class AdminController : Controller
    {
        private IBookRepository repository;

        public AdminController(IBookRepository repo )
        {
            repository = repo;
        }

        // GET: Admin
        public ViewResult Index()
        {

            return View(repository.Books);
        }

        public ViewResult Edit(int ISBN)
        {
            Book book = repository.Books.FirstOrDefault(b => b.ISBN == ISBN);
            return View(book);
        }

        [HttpPost]
        public ActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                repository.SaveBook(book);
                TempData["Message"] = book.Title + "Has Been Saved";

                return RedirectToAction("Index");
            }
            else
            {
                return View(book);
            }

        }

    }
}

BookStore.WebUI/Controllers/BookController.cs
using BookStore.Domain.Abstract;
using BookStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    public class BookController : Controller
    {

        private IBookRepository repository;
        public int PageSize = 4;


        public BookController(IBookRepository bookRep)
        {
            repository = bookRep;
        }

        public ViewResult List(string specilization, int page=1)
        {
            BookListViewModel model = new BookListViewModel
            {
                Books = repository.Books
                .Where(b => specilization == null || b.Specialization == specilization)
                .OrderBy(b => b.ISBN)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),

                PagingInfo = new Models.PagingInfo
                {
                    CurrentPage = page,
                    ItemPerPage = PageSize,
                    TotalItems =
                    specilization == null ?
                    repository.Books.Count() :
                    repository.Books.Where(b => b.Specialization == specilization).Count()
                },
                CurrentSpecilization = specilization
        };

            return View(model);
        }

        public ViewResult ListAll()
        {
            return View(repository.Books);
        }

    }

}

BookStore.WebUI/Controllers/CartController.cs
using BookStore.Domain.Abstract;
using BookStore.Domain.Entities;
using BookStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IBookRepository repository;

        private IOrderProcessor orderProcesser;

        public CartController(IBookRepository repo, IOrderProcessor pro)
        {
            repository = repo;
            orderProcesser = pro;
        }

        // GET: Cart
        public ViewResult Index(Cart cart, string returnUrl)
        {

            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }



        public RedirectToRouteResult AddToCart(Cart cart, int isbn, string returnUrl)
        {
            Book book = repository.Books
                .FirstOrDefault(b => b.ISBN == isbn);

            if (book != null)
            {
               cart.AddItem(book);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int isbn, string returnUrl)
        {
            Book book = repository.Books
               .FirstOrDefault(b => b.ISBN == isbn);
            if (book != null)
            {
                cart.RemoveLine(book);
            }
            return RedirectToAction("Index",new { returnUrl } );
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0) 
            {
                ModelState.AddModelError("", "Sorry Your Cart Is Empty");
            }

            if (ModelState.IsValid)
                {
                    orderProcesser.ProcessOrder(cart, shippingDetails);
                    cart.Clear();
                    return View("Completed");
                }
                else
                {
                    return View(shippingDetails);

                }
        
        }

    }
}

BookStore.WebUI/Controllers/NavController.cs
using BookStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IBookRepository repository;

        public NavController(IBookRepository repo)
        {
            repository = repo;
        }

        // GET: Nav
        public PartialViewResult Menu(string specilization=null)
        {
            ViewBag.SelectedSpec = specilization;
            IEnumerable<string> spec = repository.Books
                                .Select(b => b.Specialization)
                                .Distinct()
                                .OrderBy(b => b);

            
            return PartialView("FlexMenu",spec);
        }
    }
}

BookStore.WebUI/Views/Admin/Edit.cshtml
@model BookStore.Domain.Entities.Book

@{
    ViewBag.Title = "Admin: Edit ";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>
@Html.HiddenFor(b => b.ISBN)
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Book</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ISBN )

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Specialization, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Specialization, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Specialization, "", new { @class = "text-danger" })
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BookStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<BookStore.Domain.Entities.Book>

@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

    <h2>Book Store</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>

<div class="panel panel-default" >

    <div class="panel-heading">
        <h3>All Books</h3>
    </div>

    <div class="panel-body">
        <table class="table table-striped">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Specialization)
                </th>
                <th>Control</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @item.Price.ToString("c")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Specialization)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { ISBN = item.ISBN }) |
                        @Html.ActionLink("Details", "Details", new { ISBN = item.ISBN }) |
                        @Html.ActionLink("Delete", "Delete", new { ISBN = item.ISBN })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

BookStore.WebUI/Views/Book/List.cshtml
@model BookStore.WebUI.Models.BookListViewModel
@{
    ViewBag.Title = "List";
}
<h2>Book List</h2>


@foreach (var b in Model.Books)
{
    @Html.Partial("BookSummary",b)
}

<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List",new { Page = x, specilization = Model.CurrentSpecilization}))
    
</div>

BookStore.WebUI/Views/Cart/Checkout.cshtml
@model BookStore.Domain.Entities.ShippingDetails

@{
    ViewBag.Titel = "BooksStore : Checkout";
}

<h2>Checkout Now</h2>
<p>Please Enter Your Details, and We'll Ship Your Books Right Away</p>

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <h3>Ship To</h3>
    <div class="form-group">
        <label>Name:</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control " })
    </div>

    <h3>Address</h3>

    foreach (var prop in ViewData.ModelMetadata.Properties)
    {
        if (prop.PropertyName != "Name" && prop.PropertyName != "GiftWrap")
        {
            <div class="form-group">
                <label>@(prop.DisplayName ?? prop.PropertyName):</label>
                @Html.TextBox(prop.PropertyName,null, new { @class = "form-control " })
            </div>
        }
    }

    <h3>Options</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x => x.GiftWrap ) 
            Gift Wrap This Book(s)
        </label>
    </div>


    <div class="text-center " >
        <input type="submit" class="btn btn-primary"  value="Complete Order"/>
    </div>


}



@*<div class="form-group">
        <label>Line1:</label>
        @Html.TextBoxFor(x => x.Line1, new { @class = "form-control " })
    </div>
    <div class="form-group">
        <label>Line2:</label>
        @Html.TextBoxFor(x => x.Line2, new { @class = "form-control " })
    </div>
    <div class="form-group">
        <label>City</label>
        @Html.TextBoxFor(x => x.City, new { @class = "form-control " })
    </div>
    <div class="form-group">
        <label>State:</label>
        @Html.TextBoxFor(x => x.State, new { @class = "form-control " })
    </div>
    <div class="form-group">
       <label>Country:</label>
        @Html.TextBoxFor(x => x.Country, new { @class = "form-control " })
    </div>

*@

BookStore.WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Titel = "BookStore : Order Submitted";
}
<h2>welcome</h2>

BookStore.WebUI/Views/Cart/Index.cshtml
@model BookStore.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Titel = "BookStore : Your Cart";
}

<h2>Your Cart</h2>
<table class="table table-striped" id="cartTable">
    <thead class="thead-inverse">
        <tr class="">
            <th class="text-center">Item</th>
            <th class="text-center">Quanitity</th>
            <th class="text-center">Price</th>
            <th class="text-center">SubTotals</th>
        </tr>
    </thead>
    
    <tbody class="">
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Book.Title</td>
                <td class="text-center">@line.Quantity</td>
                <td class="text-center">@line.Book.Price.ToString("c")</td>
                <td class="text-center">@((line.Quantity * line.Book.Price).ToString("c"))</td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("isbn", line.Book.ISBN)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="btn btn-danger btn-sm" type="submit" value="Remove" />

                    }
                </td>
            </tr>

        }

    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right"><strong>Total:</strong></td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
   <a class="btn btn-primary" href="@(Model.ReturnUrl ?? "/Book/List")">Continue Shopping</a>

    @Html.ActionLink("Checkout Now","Checkout",null, new { @class = "btn btn-primary"})


@*@Html.ActionLink("Continue Shopping", "", "",
    new { retuenUrl = ((Model.ReturnUrl == null) ? "Book/List" : Model.ReturnUrl).ToString() },
    new { @class = "btn btn-primary" }
    )*@
</div>

BookStore.WebUI/Views/Cart/Summary.cshtml
@model BookStore.Domain.Entities.Cart

<div class="navbar-right">
    @Html.ActionLink("Checkout","Index","Cart",
    new { retuenUrl = Request.Url.PathAndQuery},
    new {@class="btn btn-default navbar-btn"}

)
</div>

<div class="navbar-text navbar-right">
    <b>Your Cart : </b>
    @Model.Lines.Sum(x => x.Quantity) Book(s),
    @Model.ComputeTotalValue().ToString("c")

</div>

BookStore.WebUI/Views/Nav/FlexMenu.cshtml
@model IEnumerable<string>

@{
    bool MopView = (bool)(ViewContext.RouteData.Values["mopLayout"] ?? false);


    string Classes = MopView ? " btn-group btn-group-sm" : null;

}


<div class="@Classes">    
    
        @Html.ActionLink("Home", "List", "Book", null,
       new { @class = MopView ? " btn btn-default btn-sm" : " btn btn-block btn-default btn-lg " })
    


    @foreach (var link in Model)
    {
        @Html.RouteLink(link,
        new { controller = "Book", Action = "List", specilization = link, page = 1 },
        new { @class = (MopView ? " btn btn-default btn-sm " : " btn btn-block btn-default btn-lg ")
        + ((link == ViewBag.SelectedSpec) ? " btn-primary " : "").ToString() })
    }
</div>

BookStore.WebUI/Views/Nav/Menu-Mop.cshtml
@model IEnumerable<string>

<div class="btn-group btn-group-sm btn-group-justified">
    @foreach (var link in Model)
    {
        @Html.RouteLink(link,
        new { controller = "Book", Action = "List", specilization = link, page = 1 },
        new { @class = "btn btn-default btn-sm " + ((link == ViewBag.SelectedSpec) ? "btn-primary" : "").ToString() })
    }
</div>

BookStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>


@foreach (var link in Model)
{
    @Html.RouteLink(link,
    new { controller= "Book", Action= "List",specilization=link, page=1},
    new { @class="btn btn-block btn-default btn-lg " + ( (link == ViewBag.SelectedSpec) ? "btn-primary": "").ToString() })
}

BookStore.WebUI/Views/Shared/BookSummary.cshtml
@model BookStore.Domain.Entities.Book

<div class="well">
     
    <h3>
        <strong>@Model.Title</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>
    <span class="lead">@Model.Description</span>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(b => b.ISBN)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery )
            <input type="submit" class="btn btn-success" value="Add To Cart" />
        </div>
    }
</div>

BookStore.WebUI/Views/Shared/_AdminLayout.cshtml
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/ErrorStyle.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container">
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()

    </div>
</body>
</html>

BookStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/ErrorStyle.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation" >
        <span class="hidden-xs">
            @Html.ActionLink("Book Store", "List", "Book", null, new { @class = "navbar-brand" })
        </span>
        <a class="navbar-brand " href="/Book/List">
            <div class="visible-xs">Book</div>
            <div class="visible-xs">Store</div>
        </a>
        @Html.Action("Summary", "Cart")
     </div>

    <div class="container">
        <div class="visible-xs">
            @Html.Action("Menu","Nav", new { mopLayout = true })
        </div>
        <div class="row panel ">
            <div id="Specialization" class="col-xs-3 hidden-xs">
                @Html.Action("Menu", "Nav")
            </div>
            <div class="container col-xs-12 col-sm-8">
                @RenderBody()

            </div>
        </div>
    </div>
   

   
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

    
</body>
</html>